gvotable: add missing prototype and reenable -Wmissing-prototypes
drivers/misc/gvotable.c:154:5: error: no previous prototype for ‘gvotable_comparator_int’ [-Werror=missing-prototypes]
  154 | int gvotable_comparator_int(void *l, void *r)
      |     ^~~~~~~~~~~~~~~~~~~~~~~

Bug: 330718746
Test: TH
Change-Id: If10ea28b00a6fc0ffa26a35baf368fde6c1da8de
Signed-off-by: André Draszik <andre.draszik@linaro.org>
Signed-off-by: Aarqw12 <lcockx@protonmail.com>