usb: phy: exynos-usbdp-gen2-v4: fix missing prototypes and reenable -Wmissing-prototypes
Deal with all the missing prototypes in this part of the Exynos phy
driver:

    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:30:6: error: no previous prototype for function 'phy_exynos_usbdp_g2_v2_tune_each' [-Werror,-Wmissing-prototypes]
       30 | void phy_exynos_usbdp_g2_v2_tune_each(struct exynos_usbphy_info
          |      ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:1554:6: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_tune' [-Werror,-Wmissing-prototypes]
     1554 | void phy_exynos_usbdp_g2_v4_tune(struct exynos_usbphy_info *info)
          |      ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:2359:5: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_internal_loopback' [-Werror,-Wmissing-prototypes]
     2359 | int phy_exynos_usbdp_g2_v4_internal_loopback(struct exynos_usbphy_info *info, u32 cmn_rate)
          |     ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:2409:6: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_eom_init' [-Werror,-Wmissing-prototypes]
     2409 | void phy_exynos_usbdp_g2_v4_eom_init(struct exynos_usbphy_info *info, u32 cmn_rate)
          |      ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:2915:6: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_eom_start' [-Werror,-Wmissing-prototypes]
     2915 | void phy_exynos_usbdp_g2_v4_eom_start(struct exynos_usbphy_info *info, u32 ph_sel, u32 def_vref)
          |      ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:2993:5: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_eom_get_done_status' [-Werror,-Wmissing-prototypes]
     2993 | int phy_exynos_usbdp_g2_v4_eom_get_done_status(struct exynos_usbphy_info *info)
          |     ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:3021:5: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_eom_get_err_cnt' [-Werror,-Wmissing-prototypes]
     3021 | u64 phy_exynos_usbdp_g2_v4_eom_get_err_cnt(struct exynos_usbphy_info *info, u32 cmn_rate)
          |     ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:3108:6: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_eom_stop' [-Werror,-Wmissing-prototypes]
     3108 | void phy_exynos_usbdp_g2_v4_eom_stop(struct exynos_usbphy_info *info)
          |      ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:3131:6: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_eom' [-Werror,-Wmissing-prototypes]
     3131 | void phy_exynos_usbdp_g2_v4_eom(struct exynos_usbphy_info *info,
          |      ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:3187:5: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_enable' [-Werror,-Wmissing-prototypes]
     3187 | int phy_exynos_usbdp_g2_v4_enable(struct exynos_usbphy_info *info)
          |     ^
    .../drivers/phy/samsung/phy-exynos-usbdp-gen2-v4.c:3237:6: error: no previous prototype for function 'phy_exynos_usbdp_g2_v4_disable' [-Werror,-Wmissing-prototypes]
     3237 | void phy_exynos_usbdp_g2_v4_disable(struct exynos_usbphy_info *info)
          |      ^

Bug: 330718746
Test: TH
Change-Id: I605795e94daf6381f34b41dcb2ea1b84f7c99b5c
Signed-off-by: André Draszik <andre.draszik@linaro.org>
Signed-off-by: Aarqw12 <lcockx@protonmail.com>